apply plugin: 'com.android.application'

android {
    namespace 'org.ea.sqrl'
    compileSdk 35
    defaultConfig {
        applicationId "org.ea.sqrl"
        minSdk 21
        targetSdk 34
        versionCode 54
        versionName "1.7.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
            version "3.22.1"
        }
    }
    installation {
        timeOutInMs 20 * 60 * 1000  // 20 minutes
        installOptions "-d", "-t"
    }
    ndkVersion '27.2.12479018'
}

dependencies {
    // Local AAR
    implementation(name: 'libsodium-jni-aar-2.0.2', ext: 'aar')

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.fragment:fragment:1.8.6'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'androidx.biometric:biometric:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    // Google
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'

    // QR code scanning
    implementation 'com.journeyapps:zxing-android-embedded:4.1.0'
    implementation 'com.google.zxing:core:3.5.3'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.1'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-accessibility:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-web:3.6.1'
    androidTestImplementation 'androidx.test.espresso.idling:idling-concurrent:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-idling-resource:3.6.1'
    androidTestImplementation 'com.google.guava:guava:33.4.0-android'
}
